server:
  port: 9092
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zippypickupanddeliverymgmtdb
    username: root
    password: root
  jpa:
    generate-ddl: false
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /apidoc
  swagger-ui:
    path: /swaggerui.html 
pickupdeliveryservice:
  api:
    security:
      username: zippyuser
      password: "$2a$10$ao9M1pLRtM06lPpRzU1SuOoVeESDiCOD/npBkFyesZN8i2P7t.F.y"
      csrf: false